### ISSUE TITLE
Subscriptions API not found

### ISSUE THREAD

**Issue by bsraya** [SERVSEC-NaN/Rewards-API#2]
`http get https://reward-api-ruby.herokuapp.com/api/v1/subscriptions`

**Comment by BrandonBenn** [comment]
There is no such association.

```http
/api/v1/subscribers/${id}
```
Will retrieve all promoters for a given subscriber.

```http
/api/v1/promoters/${id}
```
Will retrieve all subscribers for a given promoter.
